apps = [
  // {
  //   name: "banana",
  //   task: require("./banana.js"),
  //   addr: "https://t.me/OfficialBananaBot/banana?startapp=referral=5FR4HU1",
  //   interval: 3600 * 1000,
  //   launch: /\d+\/\d+/,
  // },
  // {
  //   name: "bby",
  //   task: require("./bby.js"),
  //   addr: "https://t.me/bountybay_bot/deals?startapp=invite-7d126de5",
  //   interval: 3600 * 1000,
  //   launch: /Daily Farming/,
  // },
  {
    name: "blum",
    task: require("./blum.js"),
        addr: "https://t.me/blum/app?startapp=ref_38V43x0Gjo",
    interval: 3600 * 1000,
    launch: /.*Farming.*|.*Claim.*|.*Continue.*|.*Start.*/,
  },
  {
    name: "boom",
    task: require("./boom.js"),
      addr: "https://t.me/Boom/LoudCoins?startapp=2WXZTKRRCd3XxgDTpHXA5s",
    interval: 3600 * 1000,
    launch: /(Claim.*)|(Start)|(.*omplete.*)/,
  },
  {
    name: "bums",
    task: require("./bums.js"),
      addr: "https://t.me/bums/app?startapp=ref_Xt90eLRJ",
    interval: 0.5 * 3600 * 1000,
    launch: /Nice|Play/,
  },
  {
    name: "capybara",
    task: require("./capybara.js"),
      addr: "https://t.me/Capybara_TapTap_bot?start=D1kUKqhGpY",
    interval: 2 * 3600 * 1000,
    launch: /Power/,
    extra: /Play Now！/,
  },
  {
    name: "cexio",
    task: require("./cexio.js"),
      addr: "https://t.me/cexio_tap_bot?start=1730717228794764",
    interval: 0.25 * 3600 * 1000,
    launch: /Work/,
    extra: /Start app/,
  },
  {
    name: "corn",
    task: require("./corn.js"),
      addr: "https://t.me/Corn/PlayCornBattles?startapp=2098359781",
    interval: 3600 * 1000,
    launch: "MAIN",
  },
  {
    name: "duck",
    task: require("./duck.js"),
      addr: "https://t.me/duckscoop_bot/app?startapp=DTjMoeEIZY",
    interval: 4 * 3600 * 1000,
    launch: /Home/,
  },
  {
    name: "duckChain",
    task: require("./duckChain.js"),
      addr: "https://t.me/DuckChain_bot/quack?startapp=j6DLmTYV",
    interval: 3600 * 1000,
    launch: /Home|Join.*/,
  },
  {
    name: "else",
    task: require("./else.js"),
      addr: "https://t.me/else_app_bot/start?startapp=ref=elseh4jthz24bsu9",
    interval: 3600 * 1000,
    launch: /.*Career.*/,
  },
  {
    name: "freedogs",
    task: require("./freedogs.js"),
      addr: "https://t.me/theFreeDogs_bot/app?startapp=ref_N0TudKgY",
    interval: 3600 * 1000,
    launch: /Petition/,
  },
  {
    name: "goat",
    task: require("./goat.js"),
      addr: "https://t.me/realgoats_bot/run?startapp=4f50b650-6051-47cd-ab3c-48bc5beb4d3d",

    interval: 3600 * 1000,
    launch: /Home/,
  },
  {
    name: "graphdex",
    task: require("./graphdex.js"),
      addr: "https://t.me/graph_dex_bot?start=2098359781",
    interval: 3600 * 1000,
    launch: /Farm/,
    extra: /💸 Play/,
  },
  {
    name: "hamasterKombat",
    task: require("./hamasterKombat.js"),
      addr: "https://t.me/hamster_Kombat_bot/start?startapp=kentId2098359781",
    interval: 3600 * 1000,
    launch: /(Claim)|(.*Thank you.*)|(Whats new.*)/,
  },
  {
    name: "hexn",
    task: require("./hexn.js"),
      addr: "https://t.me/hexn_bot/app?startapp=ccafb978-01cd-49a6-8134-e4634b799ede",
    interval: 0.5 * 3600 * 1000,
    launch: /🚀/,
  },
  {
    name: "lovely",
    task: require("./lovely.js"),
      addr: "https://t.me/LovelyLegends_bot/start?startapp=kentId2098359781",
    interval: 3600 * 1000,
    launch: /Friends/,
  },
  {
    name: "major",
    task: require("./major.js"),
      addr: "https://t.me/major/start?startapp=2098359781",
    interval: 3600 * 1000,
    launch:
      /(Take Bonus.*)|(.*Boost Your Rank.*)|(.*Donate Rating.*)|(.*Your Wall.*)|Top/,
  },
  {
    name: "mozo",
    task: require("./mozo.js"),
      addr: "https://t.me/MozoAI_bot?start=UFN274ig",
    interval: 3600 * 1000,
    launch: /Earn/,
    extra: /🚀 Play Now/,
  },
  {
    name: "not",
    task: require("./not.js"),
      addr: "https://t.me/NotBoredPuppies_bot?start=r_2098359781",
    interval: 3600 * 1000,
    launch: /Spin|Tasks|Play game|trophy Master/,
    extra: /🚀 Start Now! 🚀/,
  },

  {
    name: "panda",
    task: require("./panda.js"),
    addr: "https://t.me/PandaKombat_official_bot?start=bawaan",
    interval: 3600 * 1000,
    extra: /Play 🐼/,
    launch: /Boosters/,
  },
  {
    name: "pingo",
    task: require("./pingo.js"),
      addr: "https://t.me/PinGo_MiniBot/join?startapp=405R4UCL",
    interval: 3600 * 1000,
    launch: /Home/,
  },
  {
    name: "seed",
    task: require("./seed.js"),
      addr: "https://t.me/seed_coin_bot/app?startapp=2098359781",
    interval: 3600 * 1000,
    launch: /Home/,
  },

  {
    name: "tabcoin",
    task: require("./tabcoin.js"),
      addr: "https://t.me/tapcoinsbot?start=ref_imTMEE",
    interval: 3600 * 1000,
    launch: /Daily Login/,
  },
  {
    name: "tabi",
    task: require("./tabi.js"),
      addr: "https://t.me/tabizoobot/tabizoo?startapp=2098359781",
    interval: 3600 * 1000,
    launch: /Shiro/,
  },
  {
    name: "tomarket",
    task: require("./tomarket.js"),
      addr: "https://t.me/Tomarket_ai_bot/app?startapp=0002WeKB",
    interval: 3600 * 1000,
    launch: /(Continue)|(Start farming)|(Play now)|Harvest/,
  },
  {
    name: "uxlink",
    task: require("./uxlink.js"),
      addr: "https://t.me/uxlink_bot/uxlinkapp?startapp=899437061",
    interval: 3600 * 1000,
    launch: /Home/,
  },
  {
    name: "wizzwoods",
    task: require("./wizzwoods.js"),
    addr: "https://t.me/WizzwoodsBot/app?startapp=rp_1821534",
    interval: 3600 * 1000,
    launch: /.*/,
  },
  {
    name: "okx",
    task: require("./okx.js"),
      addr: "https://t.me/OKX_official_bot/OKX_Racer?startapp=linkCode_123862368",
    interval: 3600 * 1000,
    launch: /.*上涨.*/,
  },
  {
    name: "netcoin",
    task: require("./netcoin.js"),
    addr: "https://t.me/layernet_netcoin_bot/netcoin?start=bawaan",
    interval: 3600 * 1000,
    launch: /DOGS/,
  },
  // {
  //   name: "cat",
  //   task: require("./cat.js"),
  //   addr: "https://t.me/catsgang_bot/join?startapp=m15Spw_Ya8Q9zzBAAoJxE",
  //   interval: 3 * 3600 * 1000,
  //   launch: /Cats & Frens/,
  // },
];

module.exports = apps;
